
// from => to
// Initial generiert aus gendersprachekorrigieren.test.ts
export const replacementTestStrings: [string, string][] = [
    ["Die Präsidentin oder der Präsident", "Das Präsidenty"],
    ["...muss man kein_e Nahost-Expert_in sein.", "...muss man kein Nahost-Experty sein."],
    ["mit mehr als 50 Sprecher*innen", "mit mehr als 50 Sprechys"],
    ["von einigen Dutzend mehr oder eher weniger bekannten Musiker:innen unterzeichneten Aufruf", "von einigen Dutzend mehr oder eher weniger bekannten Musikys unterzeichneten Aufruf"],
    ["Journalist*innen", "Journalistys"],
    ["Medienmacher*innen", "Medienmachys"],
    ["Lehrer/innen", "Lehrys"],
    ["Lehrer(innen)", "Lehrys"],
    ["Lehrer*innen", "Lehrys"],
    ["LehrerInnen", "Lehrys"],
    ["LehrerINNen", "Lehrys"],
    ["die ganzen Lehrer*innen", "die ganzen Lehrys"],
    ["der ganzen Lehrer*innen", "der ganzen Lehrys"],
    ["den ganzen Lehrer*innen", "den ganzen Lehrys"],
    ["deren ganzen Lehrer*innen", "deren ganzen Lehrys"],
    ["eine/n Psycholog/in", "ein Psychology"],
    ["ExpertIn", "Experty"],
    ["BeamtIn", "Beamty"],
    ["AnwältInnen", "Anwältys"],
    ["WeltverbesserIn", "Weltverbessy"],
    ["JournalistInfrage", "Journalistyfrage"],
    ["der/die LehrerIn", "das Lehry"],
    ["den/die LehrerIn", "das Lehry"],
    ["des/der", "des"],
    ["dem/der", "dem"],
    ["den LehrerInnen", "den Lehrys"],
    ["einem*r Schüler*In", "einem Schüly"],
    ["deren Musiker:innen sangen", "deren Musikys sangen"],
    ["Auch wenn man sich schätzt und freundlich grüßt: Prinzipiell hat man es in der freien Bremer Szene, bei den MusikerInnen wie den VeranstalterInnen, eher mit EinzelkämpferInnen zu tun.", "Auch wenn man sich schätzt und freundlich grüßt: Prinzipiell hat man es in der freien Bremer Szene, bei den Musikys wie den Veranstaltys, eher mit Einzelkämpfys zu tun."],
    ["Kaum ausgezogen, hat sie die Straßen mit Bildern von zwei MusikerInnen dekoriert.", "Kaum ausgezogen, hat sie die Straßen mit Bildern von zwei Musikys dekoriert."],
    ["Abseitiges, Tiefsinniges & Schönes von Autor*innen und Freund*innen der taz.", "Abseitiges, Tiefsinniges & Schönes von Autorys und Freundys der taz."],
    ["Wenn Friedrich Merz Bundeskanzler wird, dann wandere ich aus in ein Land mit einer/m*x progressive*n*x Staatsoberhaupt.", "Wenn Friedrich Merz Bundeskanzler wird, dann wandere ich aus in ein Land mit einem progressiven Staatsoberhaupt."],
    ["mehr als 50 Sprecher*innen nahmen teil", "mehr als 50 Sprechys nahmen teil"],
    ["Ich habe oft das Gefühl, Solidarität mit Palästinenser*innen und Jüdinnen*Juden schließe sich aus.", "Ich habe oft das Gefühl, Solidarität mit Palästinensys und Judys schließe sich aus."],
    ["Corona-Leugner·innen", "Corona-Leugnys"],
    ["auf die globale sozial-ökologische Transformation. ", "auf die globale sozial-ökologische Transformation. "],
    ["des/der LehrerIn", "des Lehry"],
    [" Sinti*ze und Rom*nja ", " Sintys und Romys "],
    [" Muslim:a ", " Muslimy "],
    ["zum*zur Gewalttäter*in", "zum Gewalttäty"],
    ["zum/zur Gewalttäter/in", "zum Gewalttäty"],
    ["Keinem/keiner ", "Keinem "],
    ["Einem*einer ", "Einem "],
    ["Der*die ", "Das "],
    ["Ein*e ", "Ein "],
    ["ein europäische*n Wehrbeauftragte*n“ zu etablieren", "ein europäisches Wehrbeauftragty“ zu etablieren"],
    ["jede*n ", "jedes "],
    ["Lehrer und Lehrerinnen", "Lehrys"],
    ["Bürgerinnen und Bürger", "Bürgys"],
    ["Bürger und Bürgerinnen", "Bürgys"],
    ["Bürger und Bürgerin", "Bürgys"],
    ["die Bürgerin und der Bürger", "das Bürgy"],
    ["die Ärztin und der Arzt", "das Arzty"],
    ["der Arzt und die Ärztin", "die Arztys"],
    ["Bäuerinnen und Bauern", "Bauys"],
    ["Bürgervertreterinnen und -vertreter", "Bürgervertretys"],
    ["Könige und Königinnen", "Königys"],
    ["Dazwischen kulturelle Projekte wie die ABC“, ebenfalls in Bremen, ein Treffpunkt für Musikerinnen und Musiker verschiedener Länder und Kulturen.", "Dazwischen kulturelle Projekte wie die ABC“, ebenfalls in Bremen, ein Treffpunkt für Musikys verschiedener Länder und Kulturen."],
    ["Fast jeder von uns kennt die wahren Heldinnen und Helden der Krise.", "Fast jeder von uns kennt die wahren Heldys der Krise."],
    ["den Verkäuferinnen und Verkäufern im Supermarkt, die hinter", "den Verkäufys im Supermarkt, die hinter"],
    ["Dem Polizisten, der auf den Straßen für Sicherheit sorgt, der Bürgerin und dem Bürger, der hinter", "Dem Polizisten, der auf den Straßen für Sicherheit sorgt, dem Bürgy, der hinter"],
    ["Ärztinnen und Ärzte genießen in der Regel ein hohes Ansehen.", "Ärztys genießen in der Regel ein hohes Ansehen."],
    ["Den Ärztinnen und Ärzten, die Tag und Nacht bereitstehen, um Leben zu retten.", "Den Ärztys, die Tag und Nacht bereitstehen, um Leben zu retten."],
    ["Der Landtag wählt die Präsidentin oder den Präsidenten", "Der Landtag wählt das Präsidenty"],
    ["Die Leserin oder der Leser", "Das Lesy"],
    ["Sehr geehrte/r Leserin oder Leser", "Sehr geehrtes Lesy"],
    ["auf Vorschlag der Präsidentin oder des Präsidenten", "auf Vorschlag des Präsidenty"],
    ["Position des Anwenders oder der Anwenderin", "Position des Anwendys"],
    ["einer Ärztin oder eines Arztes", "eines Arztys"],
    ["\"stimme nicht zu\" antworten oder die Antworten überspringen. ", "\"stimme nicht zu\" antworten oder die Antworten überspringen. "],
    ["Gemeint waren dabei meist die Besserverdienenden.", "Gemeint waren dabei meist die Besserverdienys."],
    ["ist zwar nett für die Lesenden", "ist zwar nett für die Lesys"],
    ["voraus. Interessierte Nutzer können", "voraus. Interessierte Nutzer können"],
    ["für Studierende", "für Studentys"],
    ["für Teilnehmende", "für Teilnehmys"],
    [". Teilnehmende Frauen", ". Teilnehmende Frauen"],
    ["teilnehmende Kinder", "teilnehmende Kinder"],
    ["Dazwischen kulturelle Projekte wie die ABC“, ebenfalls in Bremen, ein Treffpunkt für \fMusikerinnen und Musiker\f verschiedener Länder und Kulturen.", "Dazwischen kulturelle Projekte wie die ABC“, ebenfalls in Bremen, ein Treffpunkt für \fMusikys\f verschiedener Länder und Kulturen."],
    ["Auch wenn man sich schätzt und freundlich grüßt: Prinzipiell hat man es in der freien Bremer Szene, bei den\fMusikerInnen\fwie den VeranstalterInnen, eher mit EinzelkämpferInnen zu tun.", "Auch wenn man sich schätzt und freundlich grüßt: Prinzipiell hat man es in der freien Bremer Szene, bei den\fMusikys\fwie den Veranstaltys, eher mit Einzelkämpfys zu tun."],
    ["Den Polizisten, die auf den Straßen für Sicherheit sorgen, den \fVerkäuferinnen und Verkäufern im Supermarkt\f, die hinter", "Den Polizisten, die auf den Straßen für Sicherheit sorgen, den \fVerkäufys im Supermarkt\f, die hinter"],
    ["Protest am Aktionstag für die \fGeflüchteten\f aus den griechischen Lagern ", "Protest am Aktionstag für die \fFlüchtlys\f aus den griechischen Lagern "],
    ["\n            abc\r\n        def\r\n gih\n ;\n        ", "\n            abc\r\n        def\r\n gih\n ;\n        "],
    ["Dem folgte am Mittwoch vor Weihnachten ein Beschluss, dass Hamburg Geflüchtete aufnehmen wolle dem Vernehmen nach 60 Kinder, außerdem sei das Land bereit, fünf Kinder aus dem nun gestarteten Bundesprogramm aufzunehmen.", "Dem folgte am Mittwoch vor Weihnachten ein Beschluss, dass Hamburg Flüchtlys aufnehmen wolle dem Vernehmen nach 60 Kinder, außerdem sei das Land bereit, fünf Kinder aus dem nun gestarteten Bundesprogramm aufzunehmen."],
    ["Der Senat soll sein Handeln gegenüber Obdachlosen, Geflüchteten und Menschen ohne Papiere überdenken.", "Der Senat soll sein Handeln gegenüber Obdachlosen, Flüchtlys und Menschen ohne Papiere überdenken."],
    ["Der Senat soll sein Handeln gegenüber AutorInnen und Geflüchteten überdenken.", "Der Senat soll sein Handeln gegenüber Autorys und Flüchtlys überdenken."],
    ["Der Senat soll sein Handeln gegenüber AutorInnen, Geflüchteten und Menschen ohne Papiere überdenken.", "Der Senat soll sein Handeln gegenüber Autorys, Flüchtlys und Menschen ohne Papiere überdenken."],
    ["Das Bündnis hatte dazu aufgerufen, mit Plakaten auf Rädern durch die Straßen zu fahren, um gegen das Elend der Geflüchteten in Lagern zu demonstrieren.", "Das Bündnis hatte dazu aufgerufen, mit Plakaten auf Rädern durch die Straßen zu fahren, um gegen das Elend der Flüchtlys in Lagern zu demonstrieren."],
    ["Protest am Aktionstag für die Geflüchteten aus den griechischen Lagern", "Protest am Aktionstag für die Flüchtlys aus den griechischen Lagern"],
    ["Bei der Räumung sollen mehrere Geflüchtete versucht haben", "Bei der Räumung sollen mehrere Flüchtlys versucht haben"],
    ["Der Geflüchtete muss in diesem Fall selbst die Verantwortung übernehmen.", "Das Flüchtly muss in diesem Fall selbst die Verantwortung übernehmen."],
    ["Das derzeitige Mühen um das Wohl Anderer endet bei den Geflüchteten in Sammelunterkünften.", "Das derzeitige Mühen um das Wohl Anderer endet bei den Flüchtlys in Sammelunterkünften."],
    ["Inwiefern beeinflusst die Sprache, wie wir den Geflüchteten begegnen?", "Inwiefern beeinflusst die Sprache, wie wir den Flüchtlys begegnen?"],
    ["Mehr und mehr Engagierte verwenden den Begriff „Geflüch­te­te“.", "Mehr und mehr Engagierte verwenden den Begriff „Flüchtlys“."],
    ["Geflüchtete Menschen beschäftigen", "Geflüchtete Menschen beschäftigen"],
    ["geflüchtete Kinder", "geflohene Kinder"],
    ["kommenden geflüchteten Kinder aus", "kommenden geflohenen Kinder aus"],
    ["Geflüchtetenlager", "Flüchtlyslager"],
    ["Sehr geehrte Interessierte", "Sehr geehrte Interessentys"],
    ["Sehr geehrte Studierende", "Sehr geehrte Studentys"],
    ["Sehr geehrte Empfänger*innen des Newsletters XY", "Sehr geehrte Empfängys des Newsletters XY"],
    ["Liebe Mitarbeitende", "Liebe Mitarbeitys"],
    ["Sehr geehrte Teilnehmende", "Sehr geehrte Teilnehmys"],
    ["Student*in ", "Studenty "],
    ["Doktor*in ", "Doktory "],
    [" Erste*r ", " Erstes "],
    [" Expert*innengespräche ", " Expertysgespräche "],
    [" Kandidat*innen ", " Kandidatys "],
    [" was eine:n selbst betrifft ", " was einen selbst betrifft "],
    ["Kundin oder Kunde", "Kundy"],
    ["Ein/eine Schülersprecher/in", "Ein Schülersprechy"],
    ["Liebe:r", "Liebes"],
    [". Stellvertrende*r Datenschutzbeauftragte*r", ". Stellvertrendes Datenschutzbeauftragty"],
    ["stellvertrende*r Datenschutzbeauftragte*r", "stellvertrendes Datenschutzbeauftragty"],
    ["Absolute*r Topleister*in", "Absolutes Topleisty"],
    [" https://lnkd.in/dummy ", " https://lnkd.in/dummy "],
    [" Baden-Baden ", " Baden-Baden "],
    ["Bordkarte(n) konnte(n)", "Bordkarte(n) konnte(n)"],
    ["Kreditkarte(n)", "Kreditkarte(n)"],
    ["2 Probestunde(n) übrig", "2 Probestunde(n) übrig"],
    ["Die Corona-Zahlen steigen und steigen: Letzte Ausfahrt Lockdown?", "Die Corona-Zahlen steigen und steigen: Letzte Ausfahrt Lockdown?"],
    ["in eine Hardware-nähere Sprache", "in eine Hardware-nähere Sprache"]
];

replacementTestStrings.push()